認証周りの実装
traPtitech/piscon-portal-v2 pull request #7
Opened 2024-12-22 06:18 UTC by pirosiki197

## やったこと
- traQ OIDC を使った認証まわりの実装をしました
- 認証成功後にトップページにリダイレクトするようにしました
- 結局 `handler` 以下に openapi のコードを出力するようにしました
- できるだけ薄めに作りたかったので、リポジトリ層は作っていません
- bob のテストが mysql だと失敗するので、テストを出力するのをやめました。そのうち修正されるとは思います

### テストについて
`task test`でテストが実行できます。CI に組み込むのは別でやります

### 動作確認について
ルートディレクトリに `.env` ファイルを作ってから`task run-server`するとサーバーが起動します

2024-12-22 12:16 UTC, ikura-hamu reviewed
bobを移行する可能性があることを考えると、repository層が欲しい気がする。repository層作れば、mock使ってDB立ち上げずにユニットテストにできるんじゃないかな。DBの起動を待ってテストの実行時間がかかるのは避けたい。

.envに書く内容をどこかに書いておいてほしい。

権限まわり(admin or 普通の人、チーム内 or チーム外)はどんな感じで実装する予定ですか。僕はmiddlewareでやるといい感じかなと思っています。

2024-12-22 12:16 UTC, ikura-hamu commented on server/handler/session.go
> +	sess.Values["session_id"] = sessID
`"session_id"`をどこかで定数で置いておきたい

2024-12-22 12:16 UTC, ikura-hamu commented on server/handler/oauth2.go
> +		_, err := models.Users.Insert(&models.UserSetter{
transactionとりたい。user作成に成功してsession作成に失敗したら変にUserが残っちゃう

2024-12-23 05:30 UTC, pirosiki197 commented
.env について README に書いておきました
権限周りはmiddlewareでチェックする予定です

2024-12-24 13:48 UTC, ikura-hamu requested changes
ちょっと多くなってしまったので、いったんこれで。直してもらったらまた詳細を見るかもです。

2024-12-24 13:48 UTC, ikura-hamu commented on README.md
> +`task run-server` で portal server が起動します。
traQのclientを作るときの設定（リダイレクト先とか権限とか）も書いておいてもらえると再現しやすくて助かります。
何番ポートに起動してあるかも（ROOT_URLに書いてあるからほぼ自明だけど）ほしいな

2024-12-24 13:48 UTC, ikura-hamu commented on Taskfile.yml
> +      - go test -cover ./...
-raceオプションもほしいな
```suggestion
      - go test -cover -race ./...
```

2024-12-24 13:48 UTC, ikura-hamu commented on Taskfile.yml
> +  rm-test-db:
これいらなそう

2024-12-24 13:48 UTC, ikura-hamu commented on Taskfile.yml
> +
↓の代わりにrm-dbかdown-dbかほしいな

2024-12-24 13:48 UTC, ikura-hamu commented on server/repository/repository.go
> +
Repositoryを分割するかはなやみどころ。意見を訊きたい

2024-12-24 13:48 UTC, ikura-hamu commented on server/services/oauth2/oauth2.go
> +	go stateStorage.Start()
https://pkg.go.dev/github.com/jellydator/ttlcache/v3#section-readme

> Note that by default, a new cache instance does not let any of its items to expire or be automatically deleted. However, this feature can be activated by passing a few additional options into the `ttlcache.New()` function and calling the `cache.Start()` method:

オプション渡さないとttlの意味がないみたいなことを言ってるけど、ここで渡してないのは意図的ですか？

2024-12-24 13:48 UTC, ikura-hamu commented on server/services/oauth2/oauth2.go
> +	go codeVerifierStorage.Start()
大丈夫だとは思うんだけど、このgoroutineがpanicするとアプリ全体が止まってしまうので、recoverを入れた方がいいのかもしれない。
```suggestion
	go func() {
    defer func() {
      if cause := recover(); cause != nil {
        log.Printf("panic") //TODO: いい感じのメッセージ
      }
    }()
    codeVerifierStorage.Start()
  }()
```

2024-12-24 13:48 UTC, ikura-hamu commented on server/handler/response.go
> +		Message: openapi.NewOptString(msg),
Internal Server Errorで原因をレスポンスに含めるのはセキュリティ的によくない（攻撃の手がかりを与えてしまう）ので、エラーメッセージはログに出し、メッセージは固定にしたいです。

2024-12-24 13:53 UTC, pirosiki197 commented on server/services/oauth2/oauth2.go
> +	go stateStorage.Start()
意図的ではないです。衝撃です。直します。

2024-12-24 13:55 UTC, pirosiki197 commented on server/services/oauth2/oauth2.go
> +func (s *Service) GetUserInfo(ctx context.Context, token *oauth2.Token) (TraQUserInfo, error) {
ポインタに統一することにします

2024-12-24 13:58 UTC, pirosiki197 commented on server/repository/repository.go
> +
分割するというのは、例えばuser, session, team などで repository を分ける、ということで合ってますか？
個人的にはユーザーとチームなどは同時に取得することもありそうなので、分けなくてもいいかなと思います。あまりにinterfaceが肥大化してきたら分けてもいいかもです。

2024-12-24 15:30 UTC, pirosiki197 commented on server/handler/response.go
> +		Message: openapi.NewOptString(msg),
メッセージを固定にするというのは、エラーによらず、常に"Internal Server Errro"を返すみたいなことですか？

2024-12-24 22:59 UTC, ikura-hamu commented on server/handler/response.go
> +		Message: openapi.NewOptString(msg),
そうです

2024-12-25 15:46 UTC, pirosiki197 commented on server/services/oauth2/oauth2.go
> +	go codeVerifierStorage.Start()
panicするということはttlcacheが動いてないということなので、そのままpanicしてしまったほうがいい気がします。もしくは、recover時に再度Startさせるか。
今回はpanicすることもほとんどないと思うので、このままにしておきたいです。

2024-12-26 07:50 UTC, pirosiki197 commented on server/handler/middleware.go
> +		return func(c echo.Context) error {
テストが書きにくかったので、SessionManagerをinterfaceに切り出しちゃいます

2024-12-26 08:31 UTC, pirosiki197 commented on server/services/oauth2/oauth2.go
> +func (s *Service) GetUserInfo(ctx context.Context, token *oauth2.Token) (TraQUserInfo, error) {
`domain.XXX`はnilチェックをしたくないので、これらだけ構造体のまま返します。

2024-12-28 08:42 UTC, ikura-hamu requested changes
アプリの処理そのものは問題ないと思います。テストとかドキュメントとかの部分でちょっと修正をお願いします

2024-12-28 08:42 UTC, ikura-hamu commented on server/repository/repository.go
> +	FindUser(ctx context.Context, id string) (domain.User, error)
それぞれのメソッドについて、どういう操作をして、どんなときにどんなエラーを返すのかをコメントで書いておいてほしいです。とくにエラーについてはコードが引き継がれたときにエラーハンドリングの抜けが出そう。

2024-12-28 08:42 UTC, ikura-hamu commented on server/handler/middleware.go
> +
アプリの処理中にユーザーIDが必要になったとき、sessionIDを取ってきてその後セッションからユーザーIDを取ってくる感じになると思うんですが、ここで`echo.Context`に渡しておいて取り出せるようにして取り出しやすくしておくのはどうですか。（このPRじゃなくて必要になったときでもいいかも）

2024-12-28 08:42 UTC, ikura-hamu commented on server/handler/middleware_test.go
> +	ctrl := gomock.NewController(t)
`t.Parallel()`で並列実行したいです。

2024-12-28 08:42 UTC, ikura-hamu commented on server/handler/handler_test.go
> +type oauth2Server struct {
これはどちらでもよいのですが、`oauth2Server`よりも`oauth2MockServer`とかの方が個人的にはしっくりきます。`oauth2Server`だとアプリとしてそういう機能があるのかと思ってしまう。testパッケージにあるからテスト用のサーバーであることはほぼ自明なので、どちらでもよいです。

2024-12-28 08:42 UTC, ikura-hamu commented on cmd/server/main.go
> +package main
このファイルをserverの中じゃなくてここに置いたのはどんな意図がありますか。

2024-12-28 12:32 UTC, pirosiki197 commented on server/handler/middleware.go
> +
よさそうです。別PRでやります

2024-12-28 12:56 UTC, pirosiki197 commented on server/handler/handler_test.go
> +type oauth2Server struct {
確かに名前にmockがある方がよさそうです。変えておきます。

2024-12-28 13:02 UTC, pirosiki197 commented on cmd/server/main.go
> +package main
Goの出しているパッケージレイアウトの例を参考にしているだけで、特に意図があるわけではないです。そのうちベンチマーカーのランナー用の`cmd/runner/main.go`を作る予定でした。エントリーポイントがわかりやすくて、共通する処理をまとめやすいかな、くらいで、`server/main.go`としてもいいと思います。
https://go.dev/doc/modules/layout#server-project

2024-12-28 14:38 UTC, ikura-hamu approved these changes

2024-12-28 14:51 UTC, merged